Repository dasch-swiss/dsp-cpe-app, pull requests merged in 2022-02, with the labels that each got.

#3 feat(primary-button): TailwindUI Primary Button (DEV-439)
  .gitignore
  Makefile
  README.md
  index.html
  src/Buttons/PrimaryButton.elm
  src/Main.elm
  src/PhotoGroove.elm
  tests/ButtonsTest.elm
  tests/PhotoGrooveTests.elm
Labels: enhancement

#4 feat(primary-button): refactors primary button (DEV-466)
  elm.json
  index.html
  src/Buttons/PrimaryButton.elm
  src/Main.elm
  tests/ButtonsTest.elm
Labels: refactor

#5 feat(playground): TailwindUI Modules Playground (DEV-446)
  assets/css/main.css
  index.html
  src/Buttons/PrimaryButton.elm
  src/Buttons/Shared.elm
  src/Main.elm
  src/TailwindPlayground.elm
Labels: enhancement

#10 chore: release v0.0.2
  CHANGELOG.md
Labels: autorelease: pending

#11 docs: fix link in changelog
  CHANGELOG.md
Labels: documentation

#6 feat(button): circular button incl. icons (DEV-444, DEV-483)
  README.md
  elm.json
  src/Buttons/Button.elm
  src/Buttons/CircularButton.elm
  src/Buttons/PrimaryButton.elm
  src/Buttons/SecondaryButton.elm
  src/Buttons/Shared.elm
  src/Buttons/WhiteButton.elm
  src/Main.elm
  src/TailwindPlayground.elm
  tests/ButtonsTest.elm
Labels: enhancement

#15 chore(main): release 0.1.0
  CHANGELOG.md
  version.txt
Labels: autorelease: pending
